ACTIVITY_TRACES = {}
TRACE_COUNT_MAX = {}
TRACE_COUNT_MIN = {}

ACTIVITY_RESOURCES = {}
RESOURCE_MAX = {}
RESOURCE_MIN = {}

DEGREE_MAX = {}
DEGREE_MIN = {}

BETWEENNESS_MAX = {}
BETWEENNESS_MIN = {}

TRACES_EVENTS = None
TRACES_TIMESTAMPS = None
DEBUG = False
NOTFOUND = 0
